---
title: "Draft Quarto document"
author: "Your Name"
format: html
---

## Header 1

```{r setup}
library(tidyverse)
library(here)
library(fs)
library(purrr)
source(here("R/functions.R"))
```

```{r}```
## Importing new data
```{r}
#| eval: false
here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```
## Exercise: Reading other files
```{r}
#| eval: false
here("data-raw/nurses-stress/stress/5C/5C_1586886712//HR.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case
  )
```
```{r}
#| eval: false
here("data-raw/nurses-stress/stress/5C/5C_1586886712//HR.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
``` 
```{r}
#| eval: false
here("data-raw/nurses-stress/stress/6B/6B_1587569373//EDA.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
``` 
## Creating a function
```{r}
#' Add two numbers together.
#'
#' @param num1 A number here.
#' @param num2 A number here.
#'
#' @return Returns the sums of two numbers
#'
add_numbers <- function(num1, num2) {
  added <- num1 + num2
  return(added)
}
```

```{r}
#' Read in one nurses' stress data file
#'
#' @param file_path A path to a data file
#'
#' @return outputs a data frame/ tibble
read <- function(file_path, max_rows = 100) {
  data <- file_path |>
    readr::read_csv(
      show_col_types = FALSE,
      name_repair = snakecase::to_snake_case,
      n_max = max_rows
    )
  return(data)
}
```

```{r}
here("data-raw/nurses-stress/stress/6B/6B_1587569373//EDA.csv.gz") |>
  read()
```

```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886712//HR.csv.gz") |>
  read()
```
## Using map
```{r}
hr_files <- here("data-raw/nurses-stress/") |>
  dir_ls(regexp = "HR.csv.gz", recurse = TRUE)

hr_files

hr_data <- hr_files |>
  map(read) |> # NO BRACKETS
  list_rbind(names_to = "file_path_id")

hr_data
```
## Exercise: Convert map to function and use on sleep
```{r}
read_all <- function(filename) {
  files <- here::here("data-raw/nurses-stress/") |>
    fs::dir_ls(regexp = filename, recurse = TRUE)

  data <- files |>
    purrr::map(read) |>
    purrr::list_rbind(names_to = "file_path_id")
  return(data)
}

read_all("HR.csv.gz")
read_all("IBI.csv.gz")
```
## Exercise: Inspect and compare the data frames
```{r}
hr_data <- read_all("HR.csv.gz")
survey_data <- here("data-raw/nurses-stress/survey-results.csv.gz") |>
  read()
hr_data
survey_data
```
```{r}
hr_data |>
  mutate(
    id = str_extract(
      file_path_id,
      pattern = "/stress/[:alnum:]{2}/"
    ) |>
      str_remove("/stress/") |>
      str_remove("/"),
    .before = file_path_id
  ) |>
  select(-file_path_id)
```
## Exercise: Convert 'get ID' code into a function
```{r}
get_participant_id <- function(data) {
  data_with_id <- data |>
    dplyr::mutate(
      id = stringr::str_extract(
        file_path_id,
        "/stress/[:alnum:]{2}/"
      ) |>
        stringr::str_remove("/stress/") |>
        stringr::str_remove("/"),
      .before = file_path_id
    ) |>
    dplyr::select(-file_path_id)
  return(data_with_id)
}

get_participant_id(hr_data)
```
## Working with across
```{r}
hr_data <- read_all("HR.csv.gz") |>
  get_participant_id()
hr_data
```

```{r}
hr_data |>
  summarise(across(where(is.numeric), list(
    mean = mean,
    median = median,
    sd = sd
  )))
```

## Woriking with dates
```{r}
hr_data |>
  mutate(
    datetime = round_date(collection_datetime,
      unit = "minute"
    ),
    .before = "collection_datetime"
  )
```
## Summarising by groups
```{r}
hr_data |>
  mutate(
    collection_datetime = round_date(
      collection_datetime,
      unit = "minute"
    )
  ) |>
  summarise(
    across(
      where(is.numeric),
      list(mean = mean, sd = sd, median = median)
    ),
    .by = c(id, collection_datetime)
  )
```
